apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - ../../base
namePrefix: dev-
namespace: dev
labels:
  - pairs:
      environment: dev

#images:
#  - name: gitlab.interactive-pioneers.de:5000/ips/commos/profile
#    newTag: '0.9.70'

patches:
  - target:
      kind: Ingress
      name: demo-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: /demo-dev